Added Purge Command
HackSquadDev/discord-python pull request #10
Opened 2022-10-03 10:31 UTC by imCHiGi

Added a command to purge/delete desired number of messages from a channel.
  -Need to have admin permissions.
  -By default it will delete last 5 messages (including the command).

2022-10-03 12:19 UTC, Arpan-206 approved these changes

2022-10-03 15:41 UTC, Predeactor commented
Hey there! Thank you for your contribution for the Discord.py bot of HackSquad!

I'd like to have a few comment about your command:

- Purge should not have a default argument (Actually 5), otherwise, when using `!purge`, 5 message will be purged and this might not be good in case someone just wanted to see the help.
- Your command should preferably have a doctoring explaining the command's purpose.
- Your command should return a feedback, telling that the purge has been completed or not.

2022-10-03 16:18 UTC, Arpan-206 requested changes

2022-10-03 16:18 UTC, Arpan-206 commented on hacksquad_discordpy/main.py
> +@bot.command()
Remove default value and add a Docstring regarding the function

2022-10-03 16:18 UTC, Arpan-206 commented on hacksquad_discordpy/main.py
> +    await ctx.channel.purge(limit=amount)
Return a message after successful completion, edits permissions to anyone with `manage messages` permission.

2022-10-03 18:45 UTC, Predeactor commented
Hey there @imCHiGi, the project has been rewrite from A to Z.
Your changes are probably out of date, do you mind updating them?

It would be nice if you can make a `moderation` cog so that it can easily be worked on more safely!

Thanks for your understanding!

2022-10-09 20:13 UTC, Predeactor commented
Closing as there was no update on this.

2022-10-09 20:13 UTC, closed without merging